definitions:
  bing_wallpaper.Article:
    type: object
info:
  contact: {}
paths:
  /api/v1/articles/{id}:
    get:
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/bing_wallpaper.Article'
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 获取bing壁纸
swagger: "2.0"
